### ISSUE TITLE
dataset and program

### ISSUE THREAD

**Issue by gloryhoper** [dengxl0520/MemSAM#6]
Dear author,I had the following problems when running the program:
1. Failed to run from utils.tools import corr, bias, std, without corresponding functions or variables in utils.tools.
2.FileNotFoundError: [Errno 2] No such file or directory: '/tmp/CAMUS_public_256/class.json'
After running preprocess_camus.py, the class.json file is not found in the generated folder and the original file, and I want to know how to get this file.
Finally about the data set. For now, we can only use CAMUS and EchoNet-Dynamic. For how to use our own avi format video dataset or jpg format image dataset, I wonder if the author will update it?

**Comment by Zong-Liang** [comment]
MARK! SAME PROBLEM!

**Comment by dengxl0520** [comment]
I'm sorry for the problems you're having, here are some answers to your questions:
1. Regarding the missing `corr bias std` function in `utils.tools`, you can add the corresponding function by yourself or comment out the corresponding evaluation code temporarily. I will update the `utils.tools` later.
2. The file `class.json`  comes from SAMUS and its contents should be:
```
{
    "EchoNet": 2,
    "CAMUS": 2
}
```
3. Due to time constraints, I may not update this feature.

**Comment by gloryhoper** [comment]
Thank you for your reply.I understand.
